services:
  decision-tree:
    image: nginx:alpine
    container_name: decision-tree
    restart: always
    env_file:
      - .env
    volumes:
      - "./src:/usr/share/nginx/html"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.decision-tree.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.decision-tree.entrypoints=websecure"
      - "traefik.http.routers.decision-tree.tls.certresolver=myresolver"
    networks:
      - web

networks:
  web:
    name: web
    external: true
